### ISSUE TITLE
keys should not be localized in drop-downs

### ISSUE THREAD

**Issue by jenshp** [moqui/moqui-framework#146]
Currently, when the string used in a key for an option inside a drop-down (or radio button) is available for translation, the translated string is used instead of the original key.
For instance, if I add following l10n record:
<moqui.basic.LocalizedMessage original="Message" locale="es" localized="Mensaje"/>
Then when using the "es" locale and accessing the /apps/my/User/Messages/FindMessage, when selecting "Mensaje" at the communicationEventTypeId drop-down, I get that the communicationEventTypeId received is "Mensaje" instead of "Message". As a consequence, the relevant items are not found in the DB.

**Comment by jonesde** [comment]
This should be fixed in moqui-framework commit #e7bb5c5 and moqui-runtime commit #4205a71. In most scenarios this wouldn't happen, ie if you specify separate @key and @text attributes on the options element under the drop-down element which is generally best to do. Note that after this change if no text (option description) is found then it defaults to the key (option key/value) and that will no longer be localized. In retrospect this is the better of the two options.

Anyway, please test and let me know if those commits resolve this for you.

**Comment by jenshp** [comment]
I still have some cases that do not work as expected:
In the attached patch to the example app one screen shows that, logging in with user John Doe, by adding a translation to the string 'Y' in the 'en' locale yields the wrong key in all three cases.

[patch1.patch.zip](https://github.com/moqui/moqui-framework/files/577084/patch1.patch.zip)

**Comment by jonesde** [comment]
Thank you for the test case, I was able to apply the patch and reproduce it. I was looking at it quickly earlier and didn't even think about the drop-down options (would apply to radio, etc too). With commit #d4ca11f in place it seems to do what you intended with the field definitions in that form. Let me know if anything is still amiss...

**Comment by jenshp** [comment]
Works great now, thanks!
